### ISSUE TITLE
ItemSelect Index of AutoListItems is 0

### ISSUE THREAD

**Issue by Alfons44** [DurtyFree/alt-V-NativeUI#11]
I want to get the Index Value of an AutoListItem on Select but the Index is Everytime 0  

Code:
```
PerformanceMenu.ItemSelect.on((item, index) => {
	alt.log("[AutoListChange] " + index, item.Text);
});
```
Output:
`[17:12:01] [AutoListChange] 0 Motor`

**Comment by DurtyFree** [comment]
@Alfons44 is this still a bug? It shouldnt happen, the index should be correct if the item data (arg 1) is correct

**Comment by DurtyFree** [comment]
Closing as there hasn't been any reply
