### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Mentanding** [DurtyFree/alt-V-NativeUI#2]
Wenn ich dein NativeUI benutz + Example Menu = Game Crash beim Connecten vom Server.

Mit: https://github.com/datWeazel/alt-V-NativeUI dieser Version funktioniert das Example Menu einwandfrei = kein Crash.

**Comment by DurtyFree** [comment]
Ich kann das leider nicht reproduzieren, hast du mir deinen resource Ordner mit dem du testest ?

**Comment by DurtyFree** [comment]
Ich schließ das erstmal, bitte mit deinem resource Ordner nochmal neu eröffnen.
