### ISSUE TITLE
UIMenuDynamicListItem - Arrows misplaced

### ISSUE THREAD

**Issue by jokeruarwentto** [DurtyFree/alt-V-NativeUI#3]
**Bug**
When you don't chose any options on a **UIMenuDynamicListItem**, the arrows are misplaced. You should any items, and the arrows are placed well.

**Step to reproduce**
`
    let array = ["0", "1"]

    let menu = new NativeUI.Menu(
      "Title",
      "Subtitle",
      new NativeUI.Point(50, 50)
    )

    let item = new NativeUI.UIMenuDynamicListItem(
      "Item Name",
      itemChangeHandle,
      "Description",
      () => array[0]
    )

    menu.AddItem(item)
`

**Screenshots**
![Arrows misplaced](https://i.imgur.com/nIOhqDG.png)

**Comment by DurtyFree** [comment]
Heya, thanks for reporting. It is now fixed in the latest update.
