### ISSUE TITLE
NativeUI as dependency in another resource "NativeUI can not invoke without 'new'"

### ISSUE THREAD

**Issue by Heady20006** [DurtyFree/alt-V-NativeUI#8]
Hey,
ich tried to exclude the NativeUI resource from some ressources in on my server.
Add it as dependency is working great.
But if im trying to build my menu with NativeUI an error occurs:

`[19:47:58][Error] [V8] Exception at NativeUI:client.js:468
[19:47:58][Error]       let point = new NativeUI.Point(50,50);
[19:47:58][Error]   TypeError: Class constructor Point cannot be invoked without 'new'`

https://prnt.sc/vdieoq

Do not know why.
I am using 'new'.

**Comment by DurtyFree** [comment]
Please show full code file
